# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0008_auto_20180729_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='body',
            field=models.TextField(blank=True, help_text=b'Request body, in case of GET request body is ignored.', null=True),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='method',
            field=models.CharField(choices=[(b'ge', b'GET'), (b'po', b'POST'), (b'pu', b'PUT'), (b'de', b'DELETE'), (b'pa', b'PATCH')], default=b'ge', help_text=b'Request method.', max_length=255),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='bearer_endpoint',
            field=models.TextField(blank=True, help_text=b'If you are using Bearer Authentication, please define your endpoint to get your Bearer token.', null=True),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='bearer_request_body',
            field=models.TextField(blank=True, help_text=b'Define your URL parameters to get access token. Learn to write query string <a href="https://en.wikipedia.org/wiki/Query_string" target="_blank">here</a>', null=True),
        ),
    ]
